<a href="https://colab.research.google.com/github/valeriavasquezv/valeriavasquez-portfolio/blob/main/TelecomX.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Proyecto** **Telecom** **X**

In [12]:
import pandas as pd

In [13]:
url = "https://raw.githubusercontent.com/valeriavasquezv/valeriavasquez-portfolio/refs/heads/main/Proyecto_TelecomX/TelecomX_Data.json"

## EXTRACCION DE LOS DATOS

In [14]:
df_telecom = pd.read_json(url)
df_telecom

,customerID,Churn,customer,phone,internet,account
0,0002-ORFBO,No,"{'gender': 'Female', 'SeniorCitizen': 0, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'One year', 'PaperlessBilling': '..."
1,0003-MKNFE,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'Yes'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
2,0004-TLHLJ,Yes,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
3,0011-IGKFF,Yes,"{'gender': 'Male', 'SeniorCitizen': 1, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
4,0013-EXCHZ,Yes,"{'gender': 'Female', 'SeniorCitizen': 1, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
...,...,...,...,...,...,...
7262,9987-LUTYD,No,"{'gender': 'Female', 'SeniorCitizen': 0, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'One year', 'PaperlessBilling': '..."
7263,9992-RRAMN,Yes,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'Yes'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
7264,9992-UJOEL,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
7265,9993-LHIEB,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Two year', 'PaperlessBilling': '..."
7266,9995-HOTOH,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'No', 'MultipleLines': 'No ph...","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Two year', 'PaperlessBilling': '..."

In [15]:
df_telecom.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   customerID  7267 non-null   object
 1   Churn       7267 non-null   object
 2   customer    7267 non-null   object
 3   phone       7267 non-null   object
 4   internet    7267 non-null   object
 5   account     7267 non-null   object
dtypes: object(6)
memory usage: 340.8+ KB

In [16]:
df_telecom.dtypes

customerID    object
Churn         object
customer      object
phone         object
internet      object
account       object
dtype: object

##TRANSFORMACIÓN DE LOS DATOS

In [20]:
churn_df = df_telecom['Churn']
pd.unique(churn_df)

#columna churn contiene valores en blanco, revisar en siguiente etapa

array(['No', 'Yes', ''], dtype=object)

In [21]:
customer_df = pd.json_normalize(df_telecom["customer"])

pd.unique(customer_df["gender"])
pd.unique(customer_df["Partner"])
pd.unique(customer_df["Dependents"])
pd.unique(customer_df["SeniorCitizen"])
pd.unique(customer_df['tenure'])

array([ 9,  4, 13,  3, 71, 63,  7, 65, 54, 72,  5, 56, 34,  1, 45, 50, 23,
       55, 26, 69, 11, 37, 49, 66, 67, 20, 43, 59, 12, 27,  2, 25, 29, 14,
       35, 64, 39, 40,  6, 30, 70, 57, 58, 16, 32, 33, 10, 21, 61, 15, 44,
       22, 24, 19, 47, 62, 46, 52,  8, 60, 48, 28, 41, 53, 68, 51, 31, 36,
       17, 18, 38, 42,  0])

In [26]:
phone_df = pd.json_normalize(df_telecom['phone'])

pd.unique(phone_df['PhoneService'])
pd.unique(phone_df['MultipleLines'])

array(['No', 'Yes', 'No phone service'], dtype=object)

In [30]:
internet_df = pd.json_normalize(df_telecom['internet'])

pd.unique(internet_df['InternetService'])
pd.unique(internet_df['OnlineSecurity'])
pd.unique(internet_df['OnlineBackup'])
pd.unique(internet_df['DeviceProtection'])
pd.unique(internet_df['TechSupport'])
pd.unique(internet_df['StreamingTV'])
pd.unique(internet_df['StreamingMovies'])

array(['No', 'Yes', 'No internet service'], dtype=object)

In [32]:
account_df = pd.json_normalize(df_telecom['account'])

pd.unique(account_df['Contract'])
pd.unique(account_df['PaperlessBilling'])
pd.unique(account_df['PaymentMethod'])
pd.unique(account_df['Charges.Monthly'])
pd.unique(account_df['Charges.Total'])

array(['593.3', '542.4', '280.85', ..., '742.9', '4627.65', '3707.6'],
      dtype=object)